---
title: Dr. Jess Sanders
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: true
    permalink: "/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: index
description: Urban Forester Extraodinaire
meta_img: min_images/trees.jpg
url: 
ga: 
gtm: 
future: true
livereload: true
markdown: kramdown
kramdown:
  auto_ids: false
theme: minima
gems:
- jekyll-feed
- jekyll-admin
- uglifier
exclude:
- Gemfile
- Gemfile.lock
- node_modules
sass:
  sass_dir: _sass
  style: compressed
