---
title: "Jess Sanders, PhD"
description: Urban Forester
meta_img:
twitter:
favicon: tree.png
baseurl: '/dr-jess-sanders'
url: 'https://ecupaio.github.io/dr-jess-sanders/'
gtm:
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
defaults:
- scope:
    path: ''
  values:
    layout: index
# collections:
#   collection-name:
#     output: true
