---
title: "Jess Sanders, PhD"
description: Urban Forester
meta_img:
email: sandersjessicar@gmail.com
favicon: tree.png
baseurl: ''
url: 'https://jessicasandersphd.com'
gtm:
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: 'posts'
  values:
    layout: blog-post
# collections:
#   collection-name:
#     output: true
